### ISSUE TITLE
Hidost Model and Detection Server

### ISSUE THREAD

**Issue by zperumal** [uvasrg/EvadeML#3]
I'm trying to reproduce your experiment and I'm having a few issues. If you have any insights into causes, I'd really appreciate any suggestions you have. 

1) When setting up the hidost classifier what model did you use (specified in project.conf > model_path . It looks like some models can be generated by running the code here: https://github.com/srndic/hidost-reproduction . Is that the right model to use, or do you have suggestions on where to find the right pkl file?

2. When trying to do  
Running step 1: "./utils/generate_ext_genome.py [classifier_name] [benign_sample_folder] [file_number] "
We encountered the following issue where the rpcxml server was not found. Are there additional setup steps to launch the detection server?

**Comment by mzweilin** [comment]
Thanks for your interest in EvadeML.

1. The model we used was kindly provided by Nedim Srndic, one of the Hidost authors. You can generate a similar model on you own since they have open sourced the code on github later.

https://github.com/srndic/hidost
https://github.com/srndic/hidost-reproduction

2. You need to start detection_agent_server.py first. I've updated the README.md.
